name: Azure Laravel Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, xml, curl, zip, mysql
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader 
      - run: php artisan config:cache
      - run: php artisan route:cache

      - name: Ensure .env exists
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          fi

      - name: Set permissions for Laravel storage
        run: chmod -R 775 storage bootstrap/cache

      - name: Generate Laravel app key
        run: php artisan key:generate --force
        env:
          APP_KEY: base64:placeholder
          APP_ENV: production
          APP_DEBUG: false

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: MPPBDUS  # change this if your app name is different
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
